/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_nog_Differentiator */

#ifndef _Included_de_nog_Differentiator
#define _Included_de_nog_Differentiator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_nog_Differentiator
 * Method:    differentiate
 * Signature: (Lde/lab4inf/wrb/Function;D)D
 */
JNIEXPORT jdouble JNICALL Java_de_nog_Differentiator_differentiate
  (JNIEnv *, jobject, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
