/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_nog_WRBObserver */

#ifndef _Included_de_nog_WRBObserver
#define _Included_de_nog_WRBObserver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_nog_WRBObserver
 * Method:    differentiate
 * Signature: (Lde/lab4inf/wrb/Function;D)D
 */
JNIEXPORT jdouble JNICALL Java_de_nog_WRBObserver_differentiate
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     de_nog_WRBObserver
 * Method:    integrate
 * Signature: (Lde/lab4inf/wrb/Function;DD)D
 */
JNIEXPORT jdouble JNICALL Java_de_nog_WRBObserver_integrate
  (JNIEnv *, jobject, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
