/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_nog_Integrator */

#ifndef _Included_de_nog_Integrator
#define _Included_de_nog_Integrator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_nog_Integrator
 * Method:    integrate
 * Signature: (Lde/lab4inf/wrb/Function;DD)D
 */
JNIEXPORT jdouble JNICALL Java_de_nog_Integrator_integrate
  (JNIEnv *, jobject, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
